version: '3'
services:
  mysql:
    env_file: ./.env
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - '3306:3306'
    networks:
      - app-network
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '8080:80'
      - '443'
    networks:
      - app-network
    # mount the static files
    volumes:
      - ./mrb:/usr/share/nginx/html/mrb:ro
  api:
    image: oricloud-app
    env_file: ./.env
    build: .
    ports:
      - '${PORT}:3001'
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - mysql
networks:
  app-network:
    driver: bridge
