version: '3'
services:
  api:
    image: oricloud-app
    build: .
    networks:
      - backend
    ports:
      - '3001:3001'

  web-cli:
    image: oricloud-app
    networks:
      - backend
    command: sh

networks:
  backend:
    driver: bridge
